# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.define :jenkins do |jenkins|
  	jenkins.vm.box = "precise64"
  	jenkins.vm.box_url = "http://files.vagrantup.com/precise64.box"
		jenkins.vm.hostname = "jenkins"
  	jenkins.vm.network :forwarded_port, guest: 8080, host: 8080
  	#jenkins.vm.network :private_network, ip: "192.168.33.10"
  	#jenkins.vm.network :public_network
  	jenkins.ssh.forward_agent = true
  	#jenkins.vm.synced_folder "../data", "/vagrant_data"
  	jenkins.vm.provider :virtualbox do |vb|
  		vb.customize ["modifyvm", :id, "--memory", "1024"]
  	end

  	jenkins.vm.provision :puppet do |puppet|
  		puppet.manifests_path = "puppet/manifests"
  		puppet.manifest_file  = "site.pp"
			puppet.module_path = "puppet/modules"
  	end
	end
end
